"""
Sigma-style detection rules mapped to MITRE ATT&CK tactics & techniques.
Each rule is evaluated against the normalized `message` (and raw) field of a log event.
"""

RULES = [
    {
        "rule_id": "R001",
        "name": "SSH Brute Force Attempt",
        "tactic": "Credential Access",
        "technique_id": "T1110",
        "technique_name": "Brute Force",
        "pattern": r"failed password|authentication failure|invalid user",
        "severity_weight": 2,
    },
    {
        "rule_id": "R002",
        "name": "PowerShell Encoded Command Execution",
        "tactic": "Execution",
        "technique_id": "T1059.001",
        "technique_name": "Command and Scripting Interpreter: PowerShell",
        "pattern": r"powershell.*(-enc|-encodedcommand|frombase64string)",
        "severity_weight": 4,
    },
    {
        "rule_id": "R003",
        "name": "Web Shell Upload / Execution",
        "tactic": "Persistence",
        "technique_id": "T1505.003",
        "technique_name": "Server Software Component: Web Shell",
        "pattern": r"\.(php|jsp|aspx)\b.*(cmd=|shell)|eval\(|system\(\$_",
        "severity_weight": 4,
    },
    {
        "rule_id": "R004",
        "name": "Ingress Tool Transfer via wget/curl",
        "tactic": "Command and Control",
        "technique_id": "T1105",
        "technique_name": "Ingress Tool Transfer",
        "pattern": r"(wget|curl)\s+.*(\.sh|\.exe|\.elf|\.bin)\b",
        "severity_weight": 3,
    },
    {
        "rule_id": "R005",
        "name": "Sudo Privilege Escalation",
        "tactic": "Privilege Escalation",
        "technique_id": "T1548.003",
        "technique_name": "Abuse Elevation Control Mechanism: Sudo and Sudo Caching",
        "pattern": r"sudo:.*command=.*(bin/bash|chmod 777|/etc/shadow|passwd)",
        "severity_weight": 3,
    },
    {
        "rule_id": "R006",
        "name": "Scheduled Task / Cron Persistence",
        "tactic": "Persistence",
        "technique_id": "T1053.005",
        "technique_name": "Scheduled Task/Job: Scheduled Task",
        "pattern": r"schtasks|crontab -e|/etc/cron\.d|at\s+\d{2}:\d{2}",
        "severity_weight": 3,
    },
    {
        "rule_id": "R007",
        "name": "Network / Port Scanning Activity",
        "tactic": "Discovery",
        "technique_id": "T1046",
        "technique_name": "Network Service Discovery",
        "pattern": r"nmap|masscan|syn scan|port scan detected",
        "severity_weight": 2,
    },
    {
        "rule_id": "R008",
        "name": "OS Credential Dumping (LSASS/Mimikatz)",
        "tactic": "Credential Access",
        "technique_id": "T1003",
        "technique_name": "OS Credential Dumping",
        "pattern": r"mimikatz|lsass\.exe.*dump|sekurlsa",
        "severity_weight": 5,
    },
    {
        "rule_id": "R009",
        "name": "Security Tooling / Firewall Disabled",
        "tactic": "Defense Evasion",
        "technique_id": "T1562.001",
        "technique_name": "Impair Defenses: Disable or Modify Tools",
        "pattern": r"(stop|disable|stopped).*(firewall|defender|antivirus|auditd|windows defender)",
        "severity_weight": 4,
    },
    {
        "rule_id": "R010",
        "name": "SQL Injection / Exploit Public-Facing App",
        "tactic": "Initial Access",
        "technique_id": "T1190",
        "technique_name": "Exploit Public-Facing Application",
        "pattern": r"union select|or 1=1|<script>|\.\./\.\./|drop table",
        "severity_weight": 4,
    },
    {
        "rule_id": "R011",
        "name": "New / Rogue Account Creation",
        "tactic": "Persistence",
        "technique_id": "T1136",
        "technique_name": "Create Account",
        "pattern": r"useradd|new user added|net user .* /add|accepted password for root",
        "severity_weight": 3,
    },
    {
        "rule_id": "R012",
        "name": "Ransomware File Encryption Indicators",
        "tactic": "Impact",
        "technique_id": "T1486",
        "technique_name": "Data Encrypted for Impact",
        "pattern": r"\.locked\b|\.encrypted\b|ransom note|readme_to_decrypt|your files have been encrypted",
        "severity_weight": 5,
    },
    {
        "rule_id": "R013",
        "name": "Lateral Movement via SSH/SCP/PsExec",
        "tactic": "Lateral Movement",
        "technique_id": "T1021.004",
        "technique_name": "Remote Services: SSH",
        "pattern": r"psexec|scp\s+.*@|ssh -o stricthostkeychecking=no",
        "severity_weight": 3,
    },
    {
        "rule_id": "R014",
        "name": "C2 Beacon / Encoded Callback",
        "tactic": "Command and Control",
        "technique_id": "T1071.001",
        "technique_name": "Application Layer Protocol: Web Protocols",
        "pattern": r"beacon|/c2/|curl -s http.*\|\s*sh|base64 -d\s*\|",
        "severity_weight": 4,
    },
    {
        "rule_id": "R015",
        "name": "Suspicious Reverse Shell",
        "tactic": "Execution",
        "technique_id": "T1059.004",
        "technique_name": "Command and Scripting Interpreter: Unix Shell",
        "pattern": r"/bin/(bash|sh) -i|nc -e /bin/|bash -c .*>&\s*/dev/tcp",
        "severity_weight": 5,
    },
]

# Extra IOC indicator keywords surfaced in the extracted-IOC panel (not full rules,
# just flagged suspicious command-line fragments worth calling out to the analyst).
IOC_KEYWORDS = [
    "-enc", "-encodedcommand", "frombase64string", "wget", "curl", "chmod 777",
    "/etc/passwd", "/etc/shadow", "union select", "eval(", "system(", "mimikatz",
    "nc -e", "powershell -nop", "certutil -urlcache", "invoke-webrequest",
]

TACTIC_ORDER = [
    "Initial Access", "Execution", "Persistence", "Privilege Escalation",
    "Defense Evasion", "Credential Access", "Discovery", "Lateral Movement",
    "Collection", "Command and Control", "Exfiltration", "Impact",
]
